/**
 * Turning the schedule into calendar entries (CLAUDE.md §7 B3).
 *
 * Kept apart from `ics.ts` so that file stays a format and nothing else: what
 * belongs in the calendar is a governance decision, how a VEVENT is spelled is
 * not, and mixing them is how a payload rule gets edited by someone fixing a
 * line-folding bug.
 *
 * Pure module: no Obsidian, no Node.
 */

import type { IcsEvent } from "./ics";
import { activeLeads, leadDates, type Occurrence } from "./schedule";

/**
 * One entry per **next** occurrence, never a year of them.
 *
 * §5.7 is explicit: materialise the next occurrence only. A calendar holding
 * every future instance of every annual review is a calendar nobody reads, and
 * regenerating it would leave the stale copies behind in Outlook.
 *
 * The UID is derived from the note's `uid`, so re-emitting after the date moves
 * *updates* the existing entry rather than adding a second one. That is the
 * whole reason §5.2 puts machine references on the uid.
 */
export function calendarEvents(schedule: readonly Occurrence[]): IcsEvent[] {
  const events: IcsEvent[] = [];

  for (const occurrence of schedule) {
    if (occurrence.date === "") continue;
    // A one-off that has already happened is history; putting it back in the
    // calendar every time the file regenerates would be noise with no action.
    if (occurrence.state === "passed") continue;

    const note = occurrence.note;
    const title = note.title === "" ? note.id : note.title;

    events.push({
      uid: `${note.uid === "" ? note.id : note.uid}@scdb-cockpit`,
      date: occurrence.date,
      // The `id` is carried in the summary for the same reason §5.11 carries it
      // in a composed email: it is the one string that lets a reply, a calendar
      // entry and a note be tied back together by hand.
      summary: `${note.id} — ${title}`,
      description: describe(occurrence),
      // `activeLeads` is the single place that decides which reminders are
      // still worth raising — a lapsed obligation gets none.
      alarms: activeLeads(occurrence),
      categories: ["SCDB", note.type],
    });
  }

  return events;
}

/**
 * The description body.
 *
 * §7 B3's governance line, in one place: refs, dates, titles and the
 * `consequence` the note already states. No note body, ever — nothing here
 * reads one.
 */
function describe(occurrence: Occurrence): string {
  const note = occurrence.note;
  const lines: string[] = [];

  if (note.consequence !== "") lines.push(note.consequence);
  if (note.owner !== "") lines.push(`Owner: ${plain(note.owner)}`);
  if (note.study !== "") lines.push(`Study: ${plain(note.study)}`);
  lines.push(
    occurrence.source === "computed"
      ? "Next occurrence computed from the recurrence rule in the vault."
      : "Date as recorded in the vault.",
  );
  lines.push("Generated by SCDB Cockpit. The vault is the working record, not the system of record.");

  return lines.join("\n");
}

/** `[[Dr A Tan]]` → `Dr A Tan`. A wikilink means nothing outside the vault. */
function plain(value: string): string {
  return value.replace(/^\[\[/, "").replace(/\]\]$/, "").split("|").pop()!.trim();
}

/** The dates each entry's alarms will land on — for the confirmation dialog. */
export function alarmPreview(occurrence: Occurrence): string[] {
  return leadDates(occurrence);
}
